version: "3.7"

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - homebase
    environment:
      - CADDY_INGRESS_NETWORKS=homebase
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data

  pihole:
    image: cbcrowe/pihole-unbound:v5.8
    networks:
      - homebase
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80"
    environment:
      - DNS1=127.0.0.1#5335
      - DNS2=127.0.0.1#5335
      - DNSSEC="true"
      - TZ=America/Sao_Paulo
      - WEBPASSWORD
    volumes:
      - etc_pihole-unbound:/etc/pihole
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d
    restart: always
    labels:
      caddy: "pi.hole.intranet"
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams}}"

volumes:
  caddy_data:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:

networks:
  homebase:
    external: true